import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";

import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import Provider from "@/components/provider/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Clean | Booking Service",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
    // appearance={{
    //     layout: {
    //         unsafe_disableDevelopmentModeWarnings: true,
    //     },
    //     elements: {
    //         footerPagesLink__terms: {
    //             display: "none",
    //         },
    //     },
    // }}
    >
      <html lang="en">
        <body className={inter.className}>
          <Provider>{children}</Provider>
        </body>
      </html>
    </ClerkProvider>
  );
}